version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/myapp

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
