version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/myapp

hooks:
  ApplicationStop:
    - runas: root
      timeout: 300
      command: "docker stop weather-app || true && docker rm weather-app || true"
  BeforeInstall:
    - runas: root
      timeout: 300
      command: "yum update -y && yum install -y docker && systemctl start docker && systemctl enable docker"
  ApplicationStart:
    - runas: root
      timeout: 300
      command: "docker run -d -p 3000:3000 --name weather-app <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/weather-app:latest"
