version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/myapp

hooks:
  ApplicationStop:
    - location: stop_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
